[package]
name = "divviup-test-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
janus_client = "0.7.5"
janus_messages = "0.7.5"
prio = "0.16.2"
tokio = "1.37.0"
url = "2.5.0"
